fix: Properly handle store flags (when replacing)
ProtonMail/gluon pull request #228
Opened 2022-11-21 14:53 UTC by jameshoulahan

2022-11-21 14:58 UTC, LBeernaertProton requested changes

2022-11-21 14:58 UTC, LBeernaertProton commented on internal/state/actions.go
> +	setSeen := make(map[bool][]imap.MessageID)
`make(map[..][..], 2)`

2022-11-21 14:58 UTC, LBeernaertProton commented on internal/state/actions.go
> +	setFlagged := make(map[bool][]imap.MessageID)
make(map[..][..], 2)

2022-11-21 15:12 UTC, jameshoulahan commented on internal/state/actions.go
> +	setSeen := make(map[bool][]imap.MessageID)
even better, replaced with 
```go
	setSeen := map[bool][]imap.MessageID{true: {}, false: {}}
```

2022-11-21 15:12 UTC, jameshoulahan commented on internal/state/actions.go
> +	setFlagged := make(map[bool][]imap.MessageID)
replaced with map literal

2022-11-22 08:03 UTC, LBeernaertProton approved these changes

2022-11-22 08:03 UTC, merged